backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow

media_folder: "static/images/uploads"  # better convention
public_folder: "/images/uploads"

collections:
  - name: "about"
    label: "About Section"
    files:
      - file: "content/about.md"
        label: "About Me"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }

  - name: "skills"
    label: "Skills"
    folder: "content/skills"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Skill Name", name: "name", widget: "string" }
